"use server";

import { collection, getDocs, writeBatch, doc } from "firebase/firestore";
import { db } from "./firebase";
import type { InventoryItemForm, Equipment, DesktopEquipment } from "./definitions";

const inventoryData: any[] = [
 {
  "RESPONSABLE": "JUAN ESCALONA",
  "CEDULA": 15158639,
  "CARGO": "SIN INFORMACION",
  "SECTOR": "SIGAL",
  "STATUS GENERAL": "MIXTO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "VIT/P3400/SIN INFORMACION/1079390/INOPERATIVO/-",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/E2350-02/A001339402/28017392/OPERATIVO/-; Monitor: VIT/ZP2200/SIN INFORMACION/28017390/OPERATIVO/-; Teclado: VIT/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Mouse: VIT/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teléfono: CISCO/SPA504G/CCQ16440WSK/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "MARLOBIS",
  "CEDULA": "SIN INFORMACION",
  "CARGO": "SIN INFORMACION",
  "SECTOR": "SIGAL",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/M21000101/A001242529/1054941/OPERATIVO/-; Monitor: SIRAGON/LED 18SS/HC101062504583/10311SS/OPERATIVO/-; Teclado: LENOVO/KU 0225/1541AS3120331081C/SIN INFORMACION/OPERATIVO/-; Mouse: VIT/DOC M696/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teléfono: NO APLICA"
 },
 {
  "RESPONSABLE": "MANUEL HERNANDEZ",
  "CEDULA": 7737772,
  "CARGO": "ANALISTA DE CONTROL DE ACTIVO",
  "SECTOR": "SIGAL",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/291002/A000471261/11065774/OPERATIVO/-; Monitor: COMPAQ/W1859/CNT008VFH9/SIN INFORMACION/OPERATIVO/-; Teclado: SIRAGON/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Mouse: VIT/MS 050OP/60702827/SIN INFORMACION/OPERATIVO/-; Teléfono: NO APLICA"
 },
 {
  "RESPONSABLE": "DELVIN MARRERO",
  "CEDULA": 13129964,
  "CARGO": "ANALISTA DE ADMINISTRACION DE FLOTA",
  "SECTOR": "SIGAL",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "Teléfono: CISCO/SPA504G/CCQ1644050H/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "FERRER DARIO",
  "CEDULA": 7739224,
  "CARGO": "ANALISTA DE INVENTARIO",
  "SECTOR": "SIGAL",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: SIRAGON/1310541P4/C060003290/1045184/OPERATIVO/-; Monitor: VIT/TFT19W80PS/AS9C7BA000345/1041598/OPERATIVO/-; Teclado: SIN INFORMACION/M800P4M/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Mouse: VIT/DOK-K5313/KBC727K1019A/SIN INFORMACION/OPERATIVO/-; Teléfono: NO APLICA"
 },
 {
  "RESPONSABLE": "IVANA SAEZ",
  "CEDULA": 27758876,
  "CARGO": "SUPERVISOR DE ADMINISTRACION DE FLOTA",
  "SECTOR": "SIGAL",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "SIRAGON/NB3300/S/I/28025563/OPERATIVO/-",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "NO APLICA"
 },
 {
  "RESPONSABLE": "ENDER TORRES",
  "CEDULA": 11450196,
  "CARGO": "ANALISTA DE CONTROL DE COMBUSTIBLE",
  "SECTOR": "S/I",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: SIRAGON/1210541P4/C0602002455/SIN INFORMACION/OPERATIVO/-; Monitor: VIT/TFT19W80PS/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teclado: HP/5K2880/B93CB0ACP58EWT/SIN INFORMACION/OPERATIVO/-; Mouse: GENIUS/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teléfono: NO APLICA"
 },
 {
  "RESPONSABLE": "EDECIO AGREDA",
  "CEDULA": 19328131,
  "CARGO": "SUPERVISOR DE ALMACEN LL/FM",
  "SECTOR": "SIGAL",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/2910-06/A000477472/18000493/OPERATIVO/-; Monitor: VIT/TFT19W80PS/A59C6BA1001776/SIN INFORMACION/OPERATIVO/-; Teclado: VIT/DOK-K5113/KBC 831 K2905A/SIN INFORMACION/OPERATIVO/-; Mouse: GENIUS/SIN INFORMACION/X74476607405/SIN INFORMACION/OPERATIVO/-; Teléfono: CISCO/SPA504G/CCQ16450YIM/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "GUSTAVO ACOSTA",
  "CEDULA": 15017120,
  "CARGO": "CAPATAZ TRANSPORTE DE PERSONAL LL",
  "SECTOR": "SALA DE OPERACIONES",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/E110-01/4000690824/SIN INFORMACION/OPERATIVO/-; Monitor: VIT/SIN INFORMACION/GLDH9HA014018/1075768/OPERATIVO/-; Teclado: IBM/SK-811/1061581/SIN INFORMACION/OPERATIVO/-; Mouse: NO SE VISUALIZA/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teléfono: AVAYA/SIN INFORMACION/SIN INFORMACION/1067758/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "LUIS ORTEGA",
  "CEDULA": 26550182,
  "CARGO": "PROGRAMADOR OPERACIONAL",
  "SECTOR": "SALA DE OPERACIONES",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/E2350/02H610M71SL/280173991/OPERATIVO/-; Monitor: VIT/ZP2200/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teclado: VIT/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Mouse: VIT/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teléfono: NO APLICA"
 },
 {
  "RESPONSABLE": "FRANCO WILMER",
  "CEDULA": 11249042,
  "CARGO": "INSPECTOR OPERACIONAL",
  "SECTOR": "SALA DE OPERACIONES",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/M2100-01-01/18001286/1075807/OPERATIVO/-; Monitor: VIT/SIN INFORMACIO/NO APLICA/59C7BA007978/11085776/OPERATIVO/-; Teclado: HP/KU 0316/BC3720EVBVX0YA/SIN INFORMACION/OPERATIVO/-; Mouse: GENIUS/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teléfono: AVAYA/NTY505/11WZ112501H9/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "JOAN BARRERA",
  "CEDULA": 12844648,
  "CARGO": "PROGRAMADOR OPERACIONAL",
  "SECTOR": "SALA DE OPERACIONES",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/M2100-01-01/A001226903/18001285/OPERATIVO/-; Monitor: VIT/I90LM00006/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teclado: VIT/DOK-S318U/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Mouse: VIT/DOC M696/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teléfono: CISCO/SPA504G/CCQ16440TKN/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "CARLOS URDANETA",
  "CEDULA": 14496254,
  "CARGO": "INSPECTOR OPERACIONAL",
  "SECTOR": "SALA DE OPERACIONES",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: NO SE VISUALIZA/SIN INFORMACION/1053939/OPERATIVO/-; Monitor: LG/W1943CV/SIN INFORMACION/2085349/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "YORJHAN SALAS",
  "CEDULA": 22136577,
  "CARGO": "CAPATAZ DE MANTENIMIENTO",
  "SECTOR": "TALLER MTTO PESADA",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: SIRAGON/1320AMD2650E/11011215950P0569/SIN INFORMACION/OPERATIVO/-; Monitor: HP/GG458A/CNK8260YM2/SIN INFORMACION/OPERATIVO/-; Teclado: VIT/DOK-K5313/KBH821K10868A/SIN INFORMACION/OPERATIVO/-; Mouse: VIT/DOK-M696/MSH209K10922A/SIN INFORMACION/OPERATIVO/-; Teléfono: CISCO/SPA504G/CCQ16470U18/SIN INFORMACION/OPERATIVO/-",
  "OBSERVACIONES GENERALES": "SIN USO, CONTROLADORES"
 },
 {
  "RESPONSABLE": "ALBERTO FUENTES",
  "CEDULA": 8701202,
  "CARGO": "SUPERVISOR PROGRAMACION COSTA TJ/LL",
  "SECTOR": "SALA DE MTTO",
  "STATUS GENERAL": "MIXTO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: SIRAGON/DOK-K5318U/KBH820K1169IA/SIN INFORMACION/OPERATIVO/-; Monitor: VIT/TFTY19W80PS/A59C4BA006530/SIN INFORMACION/OPERATIVO/-; Teclado: VIT/DOK-M696/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teléfono: NO SE VISUALIZA/SIN INFORMACION/63616/SIN INFORMACION/OPERATIVO/-; Teclado: IBM/SK-8811/2349810/SIN INFORMACION/INOPERATIVO/-"
 },
 {
  "RESPONSABLE": "FERNANDO AGUSTIN",
  "CEDULA": 18795357,
  "CARGO": "SUPERVISOR DE FLOTAS Y PLANES DE MTTO",
  "SECTOR": "SALA DE MTTO",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "VIT/M2421/A000369690/2801699/OPERATIVO/-",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "Teléfono: CISCO/SPA504G/CCQ16440TIV/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "EMETERIO NAVARRO",
  "CEDULA": 10601747,
  "CARGO": "INSPECTOR DE CALIDAD OCC/LS",
  "SECTOR": "SALA DE MTTO",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: SIRAGON/SIN INFORMACION/SIN INFORMACION/2082125/OPERATIVO/-; Monitor: HP/L1706/CNK74510L0/SIN INFORMACION/OPERATIVO/-; Teclado: IBM/KB-0225/426742/SIN INFORMACION/OPERATIVO/-; Mouse: VIT/DOK-M696/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "CARLOS ROJAS",
  "CEDULA": 10088982,
  "CARGO": "INSPECTOR DE CALIDAD OCC/LS",
  "SECTOR": "SALA DE MTTO",
  "STATUS GENERAL": "ROBADO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: HP/COMPAQ/MXJS4602YQ/1042155/OPERATIVO/-; Monitor: NO SE VISUALIZA/SIN INFORMACION/11065347/SIN INFORMACION/OPERATIVO/-; Teclado: VIT/DOK-KS3180/KBH820K10844A/SIN INFORMACION/OPERATIVO/-; Mouse: SIN INFORMACION/M028U0/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-",
  "OBSERVACIONES GENERALES": "EQUIPO REPORTADO COMO ROBADO"
 },
 {
  "RESPONSABLE": "RICHARD BRACHO",
  "CEDULA": "SIN INFORMACION",
  "CARGO": "SIN INFORMACION",
  "SECTOR": "CONTRATACION",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: SIRAGON/1210-541-P4/C0602002831/SIN INFORMACION/OPERATIVO/-; Monitor: HP/COMPAQ LE190wl/3CQ0441JNY/SIN INFORMACION/OPERATIVO/-; Teclado: HP/SK-2880/B93CB0ACPS8G91/SIN INFORMACION/OPERATIVO/-; Teléfono: CISCO/SPA504G/CBT154705RT/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "INDIRA CUBILLAN",
  "CEDULA": 15401930,
  "CARGO": "SUPERVISOR DE SERVICIOS TECNICOS OPERACIONAL",
  "SECTOR": "CONTRATACION",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/M2100-01-01/SIN INFORMACION/1077140/OPERATIVO/-; Monitor: LENOVO/L197wA/U1BK709/SIN INFORMACION/OPERATIVO/-; Teclado: HP/KU-0316/BAUHR0IGAZR1FL/SIN INFORMACION/OPERATIVO/-; Mouse: MOUSE/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "BRAYAN CARRILLO",
  "CEDULA": 25555326,
  "CARGO": "ANALISTA DE SERVICIOS TECNICOS",
  "SECTOR": "CONTRATACION",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: HP/Z200/2UA1071NOY/1031268/OPERATIVO/-; Monitor: HP/L1950/CNK82701MS/1016708/OPERATIVO/-; Teclado: IBM/KB-0225/446044/SIN INFORMACION/OPERATIVO/-; Mouse: LENOVO/MO28UO/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "EDECIO QUERO",
  "CEDULA": 11889669,
  "CARGO": "CAPATAZ TRANSPORTE DE PERSONAL LL",
  "SECTOR": "CONTRATACION",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: HP/Z200/2UA1071B1K/SIN INFORMACION/OPERATIVO/-; Monitor: VIT/TFT20W90PS1/GKQHAHA012507/SIN INFORMACION/OPERATIVO/-; Teclado: VIT/JME7050/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Mouse: VIT/MSU0718T/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "ORLANDO VELASQUEZ",
  "CEDULA": 14085245,
  "CARGO": "CAPATAZ TRANSPORTE DE PERSONAL OCC",
  "SECTOR": "CONTRATacion",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/M2100-01-01/A001227968/18001214/OPERATIVO/-; Monitor: VIT/SIN INFORMACION/GLOHSHAD15804/SIN INFORMACION/OPERATIVO/-; Teclado: LENOVO/SK-8825/5199741/SIN INFORMACION/OPERATIVO/-; Mouse: AOC/MS121/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-",
  "OBSERVACIONES GENERALES": "TECLADO DE TLA"
 },
 {
  "RESPONSABLE": "TRANSCRITORES TP",
  "CEDULA": "SIN INFORMACION",
  "CARGO": "SIN INFORMACION",
  "SECTOR": "CONTRATACION",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: LENOVO/THINKCENTER/9481AS6 LKLCYBC/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "ARGENIS MALAVE",
  "CEDULA": 11946913,
  "CARGO": "CAPATAZ LIQUIDOS Y ACHIQUES",
  "SECTOR": "TLA",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/2910-02/E00VIT2910-02-01/1004890/OPERATIVO/-; Monitor: HP/1755/CNK5431CXM/SIN INFORMACION/OPERATIVO/-; Teclado: HP/KB-0316/BC3370CVBUX82T/SIN INFORMACION/OPERATIVO/-; Mouse: XTECH/ID010XTK18/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teléfono: CISCO/SPA/CCQ16440WUR/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "POOL",
  "CEDULA": "SIN INFORMACION",
  "CARGO": "SIN INFORMACION",
  "SECTOR": "SALA DE CAPATAZ TP",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/2910-02/E00VIT2910-02-01/1052648/OPERATIVO/-; Monitor: VIT/TFT19W80PS/A59C6BA015268/SIN INFORMACION/OPERATIVO/-; Teclado: VIT/JME-7050/KB7726842628A/SIN INFORMACION/OPERATIVO/-; Teléfono: CISCO/SPA/CCQ16440XG4/SIN INFORMACION/OPERATIVO/-",
  "OBSERVACIONES GENERALES": "PANTALLA TLA"
 },
 {
  "RESPONSABLE": "SUHEIN PERDOMO",
  "CEDULA": "SIN INFORMACION",
  "CARGO": "SUPERVISOR DE PLANIFICACION",
  "SECTOR": "GERENCIA",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "Teléfono: CISCO/SPA/CCQ16440XG4/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "JOSE MANUEL HERNANDEZ",
  "CEDULA": 7737772,
  "CARGO": "ANALISTA DE ADMINISTRACION DE FLOTA",
  "SECTOR": "SALA VIEJA ACTIVO",
  "STATUS GENERAL": "INOPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "SIN INFORMACION",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "Teléfono: CORTELCO/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/-"
 },
 {
  "RESPONSABLE": "JOSE DANIEL SALAZAR",
  "CEDULA": 18695682,
  "CARGO": "ANALISTA CONTROL Y SUMIN COMB Y LUBRIC",
  "SECTOR": "SALA DE COMBUSTIBLE",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: LENOVO/MT-M 9702-AB7/LKLYGFF/SIN INFORMACION/OPERATIVO/-; Monitor: VIT/SIN INFORMACION/GKQHAHA006584/SIN INFORMACION/OPERATIVO/-; Teclado: HP/KU-0316/BAUHRGIVBZT5HB/SIN INFORMACION/OPERATIVO/-; Mouse: HP/M-UAE90/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teléfono: NO APLICA"
 },
 {
  "RESPONSABLE": "YURVIN NAVA",
  "CEDULA": 20457294,
  "CARGO": "SUPERVISOR DE COMBUSTIBLE",
  "SECTOR": "SALA DE COMBUSTIBLE",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/M2100-01-01/A001241905/1078412/OPERATIVO/-; Monitor: SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teclado: VIT/DOK-K5318U/KBH820K10774A/SIN INFORMACION/OPERATIVO/-; Mouse: GENIUS/GM-080025/X71200909083/SIN INFORMACION/OPERATIVO/-; Teléfono: NO APLICA"
 },
 {
  "RESPONSABLE": "JESUS RIVERO",
  "CEDULA": 17825884,
  "CARGO": "ANALISTA CALIDAD PRODUCTIV",
  "SECTOR": "CONTRATACION",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: HP/Z200/2UA10717TH/2896/OPERATIVO/-; Monitor: HP/L1950/CNK82703C5/1016703/OPERATIVO/-; Teclado: HP/SK-2880/B93CB0ACPS7IU0/SIN INFORMACION/OPERATIVO/-; Mouse: AOC/MS121/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teléfono: CORTELCO/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "MANUEL BRITO",
  "CEDULA": "SIN INFORMACION",
  "CARGO": "SUPERVISOR DE PRESUPUESTO",
  "SECTOR": "CONTRATACION",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: HP/SIN INFORMACION/MXJ54500X3/1042156/OPERATIVO/-; Monitor: VIT/TFT19W80PS/A59C7BA007765/SIN INFORMACION/OPERATIVO/-; Teclado: VIT/SIN INFORMACION/KBC523K11638A/SIN INFORMACION/OPERATIVO/-; Mouse: VIT/SIN INFORMACION/NO SE VISUALIZA/SIN INFORMACION/OPERATIVO/-; Teléfono: SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/639027/OPERATIVO/-"
 },
 {
  "RESPONSABLE": "CARLOS ROJAS",
  "CEDULA": "SIN INFORMACION",
  "CARGO": "SIN INFORMACION",
  "SECTOR": "SALA MTTO LAGUNILLAS",
  "STATUS GENERAL": "OPERATIVO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/2600/A000006149/SIN INFORMACION/OPERATIVO/-; Monitor: VIT/190LM00006/C18D7BA015125/1069867/OPERATIVO/-; Teclado: LENOVO/SK-8820/4227115/SIN INFORMACION/OPERATIVO/-; Mouse: NO APLICA; Teléfono: SIN INFORMACION"
 },
 {
  "RESPONSABLE": "JUAN CARIELIS",
  "CEDULA": "SIN INFORMACION",
  "CARGO": "SIN INFORMACION",
  "SECTOR": "SALA MTTO LAGUNILLAS",
  "STATUS GENERAL": "MIXTO",
  "EQUIPO 1: LAPTOP (Marca/Modelo/Serial/Etiqueta/Status/Obs)": "NO APLICA",
  "EQUIPO 2: ESCRITORIO (CPU/Monitor/Teclado/Mouse/Teléfono)": "CPU: VIT/2600/A000006307/1026/INOPERATIVO/-; Monitor: VIT/TFT19W80PS/A59C7BA007729/1052950/OPERATIVO/-; Teclado: HP/KB57211/BDMGH0CHH6PSQ8/SIN INFORMACION/OPERATIVO/-; Mouse: T-WOLF/SIN INFORMACION/SIN INFORMACION/SIN INFORMACION/OPERATIVO/-; Teléfono: NO APLICA",
  "OBSERVACIONES GENERALES": "MEMORIA RAM"
 }
]
